services:
    php:
        build:
            context: docker/php
        volumes:
            - ./:/var/www/:cached
        ports:
            - 80:8000

    postgres:
        build:
            context: docker/postgres
        ports:
            - "54320:5432"
        environment:
            - EDITOR=vim
            - POSTGRES_PASSWORD=secret
        volumes:
            - pg-data:/var/lib/postgresql/data
            - ./docker/postgres/share:/var/lib/postgresql/share

    node:
        build:
            context: docker/node
        volumes:
            - ./:/var/www:cached
        ports:
            - 5173:5173

    mailpit:
        image: "axllent/mailpit:latest"
        ports:
            - "${FORWARD_MAILPIT_PORT:-1025}:1025"
            - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"

volumes:
    pg-data:
